// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfivektuskiybvnoaqra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmaXZla3R1c2tpeWJ2bm9hcXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MDI1ODgsImV4cCI6MjA1NzI3ODU4OH0.NlkgAv5v7KdrekrwMcQurJzqPb_4d1lhBZb2TBGPTLE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);